<?php
use Bitrix\Main\Loader;
Loader::registerAutoloadClasses('prospektweb.calc', [
    'Prospektweb\\Calc\\Calculator\\CalculatorInterface' => 'lib/Calculator/CalculatorInterface.php',
    'Prospektweb\\Calc\\Calculator\\BaseCalculator' => 'lib/Calculator/BaseCalculator.php',
    'Prospektweb\\Calc\\Calculator\\CalculatorRegistry' => 'lib/Calculator/CalculatorRegistry.php',
    'Prospektweb\\Calc\\Calculator\\Calculators\\DigitalSheet' => 'lib/Calculator/Calculators/DigitalSheet.php',
    'Prospektweb\\Calc\\Calculator\\Calculators\\RollLamination' => 'lib/Calculator/Calculators/RollLamination.php',
    'Prospektweb\\Calc\\Calculator\\Calculators\\DimensionsWeight' => 'lib/Calculator/Calculators/DimensionsWeight.php',
    'Prospektweb\\Calc\\Calculator\\Calculators\\PriceSettings' => 'lib/Calculator/Calculators/PriceSettings.php',
    'Prospektweb\\Calc\\Calculator\\InitPayloadService' => 'lib/Calculator/InitPayloadService.php',
    'Prospektweb\\Calc\\Calculator\\SaveHandler' => 'lib/Calculator/SaveHandler.php',
    'Prospektweb\\Calc\\Calculator\\CalculationHistoryHandler' => 'lib/Calculator/CalculationHistoryHandler.php',
    'Prospektweb\\Calc\\Config\\ConfigManager' => 'lib/Config/ConfigManager.php',
    'Prospektweb\\Calc\\Config\\SettingsManager' => 'lib/Config/SettingsManager.php',
    'Prospektweb\\Calc\\Install\\Installer' => 'lib/Install/Installer.php',
    'Prospektweb\\Calc\\Install\\SnapshotManager' => 'lib/Install/SnapshotManager.php',
    'Prospektweb\\Calc\\Services\\EntityLoader' => 'lib/Services/EntityLoader.php',
    'Prospektweb\\Calc\\Services\\ResultWriter' => 'lib/Services/ResultWriter.php',
    'Prospektweb\\Calc\\Services\\ValidationService' => 'lib/Services/ValidationService.php',
    'Prospektweb\\Calc\\Services\\DependencyTracker' => 'lib/Services/DependencyTracker.php',
    'Prospektweb\\Calc\\Services\\SyncVariantsHandler' => 'lib/Services/SyncVariantsHandler.php',
    'Prospektweb\\Calc\\Services\\DetailHandler' => 'lib/Services/DetailHandler.php',
    'Prospektweb\\Calc\\Services\\CustomFieldsService' => 'lib/Services/CustomFieldsService.php',
    'Prospektweb\\Calc\\Services\\PresetEnrichmentService' => 'lib/Services/PresetEnrichmentService.php',
    'Prospektweb\\Calc\\Services\\CatalogPriceService' => 'lib/Services/CatalogPriceService.php',
    'Prospektweb\\Calc\\Services\\OfferUpdateService' => 'lib/Services/OfferUpdateService.php',
    'Prospektweb\\Calc\\Services\\SaveAllService' => 'lib/Services/SaveAllService.php',
    'Prospektweb\\Calc\\Services\\BatchRecalculateService' => 'lib/Services/BatchRecalculateService.php',
    'Prospektweb\\Calc\\Handlers\\AdminHandler' => 'lib/Handlers/AdminHandler.php',
    'Prospektweb\\Calc\\Handlers\\DependencyHandler' => 'lib/Handlers/DependencyHandler.php',
    'Prospektweb\\Calc\\Diagnostic\\ModuleDiagnostic' => 'lib/Diagnostic/ModuleDiagnostic.php',
    'Prospektweb\\Calc\\Diagnostic\\GitHubClient' => 'lib/Diagnostic/GitHubClient.php',
    'Prospektweb\\Calc\\Diagnostic\\DiagnosticCache' => 'lib/Diagnostic/DiagnosticCache.php',
    'Prospektweb\\Calc\\Integration\\OptionMigrator' => 'lib/Integration/OptionMigrator.php',
    'Prospektweb\\Calc\\Integration\\ManagedFileInstaller' => 'lib/Integration/ManagedFileInstaller.php',
    'Prospektweb\\Calc\\Integration\\ConsolidationManager' => 'lib/Integration/ConsolidationManager.php',
    'Prospektweb\\Calc\\Integration\\TemplatePatchCoordinator' => 'lib/Integration/TemplatePatchCoordinator.php',

    'Prospektweb\\Frontcalc\\Admin\\ProductCardButton' => 'features/frontend/lib/Admin/ProductCardButton.php',
    'Prospektweb\\Frontcalc\\Service\\CalculatorAvailability' => 'features/frontend/lib/Service/CalculatorAvailability.php',
    'Prospektweb\\Frontcalc\\Service\\AccessScenarioResolver' => 'features/frontend/lib/Service/AccessScenarioResolver.php',
    'Prospektweb\\Frontcalc\\Service\\FrontendAssets' => 'features/frontend/lib/Service/FrontendAssets.php',
    'Prospektweb\\Frontcalc\\Service\\VolumeQuantityResolver' => 'features/frontend/lib/Service/VolumeQuantityResolver.php',
    'Prospektweb\\Frontcalc\\Service\\ProductAccessValidator' => 'features/frontend/lib/Service/ProductAccessValidator.php',
    'Prospektweb\\Frontcalc\\Service\\CalcServerClient' => 'features/frontend/lib/Service/CalcServerClient.php',
    'Prospektweb\\Frontcalc\\Service\\CalcServerBatchResultValidator' => 'features/frontend/lib/Service/CalcServerBatchResultValidator.php',
    'Prospektweb\\Frontcalc\\Service\\CalcServerBatchProcessor' => 'features/frontend/lib/Service/CalcServerBatchProcessor.php',
    'Prospektweb\\Frontcalc\\Service\\PresetPriceCalculator' => 'features/frontend/lib/Service/PresetPriceCalculator.php',
    'Prospektweb\\Frontcalc\\Service\\VirtualOfferBatchBuilder' => 'features/frontend/lib/Service/VirtualOfferBatchBuilder.php',
    'Prospektweb\\Frontcalc\\Service\\CustomSelectionValidator' => 'features/frontend/lib/Service/CustomSelectionValidator.php',
    'Prospektweb\\Frontcalc\\Service\\CalculationSessionStore' => 'features/frontend/lib/Service/CalculationSessionStore.php',
    'Prospektweb\\Frontcalc\\Service\\DeadlineAdjustmentNormalizer' => 'features/frontend/lib/Service/DeadlineAdjustmentNormalizer.php',
    'Prospektweb\\Frontcalc\\Service\\ServerQuoteCalculator' => 'features/frontend/lib/Service/ServerQuoteCalculator.php',
    'Prospektweb\\Frontcalc\\Config\\ConfigManager' => 'features/frontend/lib/Config/ConfigManager.php',
    'Prospektweb\\Frontcalc\\Calculator\\PropertyPayloadLoader' => 'features/frontend/lib/Calculator/PropertyPayloadLoader.php',
    'Prospektweb\\Frontcalc\\Calculator\\ElementDataService' => 'features/frontend/lib/Calculator/ElementDataService.php',
    'Prospektweb\\Frontcalc\\Calculator\\InitPayloadService' => 'features/frontend/lib/Calculator/InitPayloadService.php',

    'Prospektweb\\PropValManager\\Service\\ModuleConfig' => 'features/property_values/lib/Service/ModuleConfig.php',
    'Prospektweb\\PropValManager\\Service\\PropertyManager' => 'features/property_values/lib/Service/PropertyManager.php',
    'Prospektweb\\PropValManager\\Service\\PropertyValueDescriptionInstaller' => 'features/property_values/lib/Service/PropertyValueDescriptionInstaller.php',
    'Prospektweb\\PropValManager\\Service\\PropertyValueDescriptionRepository' => 'features/property_values/lib/Service/PropertyValueDescriptionRepository.php',
    'Prospektweb\\PropValManager\\Service\\PropertyDescriptionService' => 'features/property_values/lib/Service/PropertyDescriptionService.php',
    'Prospektweb\\PropValManager\\Service\\PropertyDescriptionJsonExporter' => 'features/property_values/lib/Service/PropertyDescriptionJsonExporter.php',
    'Prospektweb\\PropValManager\\Service\\AdminPropertySettingsExtension' => 'features/property_values/lib/Service/AdminPropertySettingsExtension.php',
    'Prospektweb\\PropValManager\\Service\\PublicJsonConfigExtension' => 'features/property_values/lib/Service/PublicJsonConfigExtension.php',

    'Prospektweb\\OfferFilter\\OfferFilter' => 'features/offers/lib/offerfilter.php',

    'Prospektweb\\LayoutFiles\\Config' => 'features/orders/lib/Config.php',
    'Prospektweb\\LayoutFiles\\FileManager' => 'features/orders/lib/FileManager.php',
    'Prospektweb\\LayoutFiles\\EventHandlers' => 'features/orders/lib/EventHandlers.php',
    'Prospektweb\\LayoutFiles\\DesiredReceiveDateManager' => 'features/orders/lib/DesiredReceiveDateManager.php',
    'Prospektweb\\LayoutFiles\\Logger' => 'features/orders/lib/Logger.php',
    'Prospektweb\\LayoutFiles\\BackupManager' => 'features/orders/lib/BackupManager.php',
    'Prospektweb\\LayoutFiles\\Agent' => 'features/orders/lib/Agent.php',
    'Prospektweb\\LayoutFiles\\Service\\YandexDiskClient' => 'features/orders/lib/Service/YandexDiskClient.php',
    'Prospektweb\\LayoutFiles\\Internals\\LayoutFileTable' => 'features/orders/lib/Internals/LayoutFileTable.php',
]);

// Примечание: Обработчик OnBuildGlobalMenu регистрируется только через persistent handler
// в install/index.php->installEvents(). Runtime регистрация через addEventHandler убрана,
// чтобы избежать дублирования пунктов меню.
