<?php
use Bitrix\Main\Loader;
Loader::registerAutoloadClasses('prospektweb.calc', [
    'Prospektweb\\Calc\\Calculator\\CalculatorInterface' => 'lib/Calculator/CalculatorInterface.php',
    'Prospektweb\\Calc\\Calculator\\BaseCalculator' => 'lib/Calculator/BaseCalculator.php',
    'Prospektweb\\Calc\\Calculator\\CalculatorRegistry' => 'lib/Calculator/CalculatorRegistry.php',
    'Prospektweb\\Calc\\Calculator\\Calculators\\DigitalSheet' => 'lib/Calculator/Calculators/DigitalSheet.php',
    'Prospektweb\\Calc\\Calculator\\Calculators\\RollLamination' => 'lib/Calculator/Calculators/RollLamination.php',
    'Prospektweb\\Calc\\Calculator\\Calculators\\DimensionsWeight' => 'lib/Calculator/Calculators/DimensionsWeight.php',
    'Prospektweb\\Calc\\Calculator\\Calculators\\PriceSettings' => 'lib/Calculator/Calculators/PriceSettings.php',
    'Prospektweb\\Calc\\Calculator\\InitPayloadService' => 'lib/Calculator/InitPayloadService.php',
    'Prospektweb\\Calc\\Config\\ConfigManager' => 'lib/Config/ConfigManager.php',
    'Prospektweb\\Calc\\Config\\SettingsManager' => 'lib/Config/SettingsManager.php',
    'Prospektweb\\Calc\\Install\\SnapshotManager' => 'lib/Install/SnapshotManager.php',
    'Prospektweb\\Calc\\Install\\SchemaRepairService' => 'lib/Install/SchemaRepairService.php',
    'Prospektweb\\Calc\\Install\\AssignmentGuardActivationService' => 'lib/Install/AssignmentGuardActivationService.php',
    'Prospektweb\\Calc\\Services\\PriceSettingsPresetService' => 'lib/Services/PriceSettingsPresetService.php',
    'Prospektweb\\Calc\\Services\\EntityLoader' => 'lib/Services/EntityLoader.php',
    'Prospektweb\\Calc\\Services\\ValidationService' => 'lib/Services/ValidationService.php',
    'Prospektweb\\Calc\\Services\\DependencyTracker' => 'lib/Services/DependencyTracker.php',
    'Prospektweb\\Calc\\Services\\SyncVariantsHandler' => 'lib/Services/SyncVariantsHandler.php',
    'Prospektweb\\Calc\\Services\\DetailHandler' => 'lib/Services/DetailHandler.php',
    'Prospektweb\\Calc\\Services\\CustomFieldsService' => 'lib/Services/CustomFieldsService.php',
    'Prospektweb\\Calc\\Services\\PresetEnrichmentService' => 'lib/Services/PresetEnrichmentService.php',
    'Prospektweb\\Calc\\Services\\CatalogPriceService' => 'lib/Services/CatalogPriceService.php',
    'Prospektweb\\Calc\\Services\\OfferUpdateService' => 'lib/Services/OfferUpdateService.php',
    'Prospektweb\\Calc\\Services\\CalculatorInputSourceCatalogService' => 'lib/Services/CalculatorInputSourceCatalogService.php',
    'Prospektweb\\Calc\\Services\\CalculatorInputMappingService' => 'lib/Services/CalculatorInputMappingService.php',
    'Prospektweb\\Calc\\Services\\StageVariantMappingService' => 'lib/Services/StageVariantMappingService.php',
    'Prospektweb\\Calc\\Services\\CatalogCalculationScenarioService' => 'lib/Services/CatalogCalculationScenarioService.php',
    'Prospektweb\\Calc\\Services\\CatalogOutputMappingService' => 'lib/Services/CatalogOutputMappingService.php',
    'Prospektweb\\Calc\\Services\\CatalogCalculationWriteService' => 'lib/Services/CatalogCalculationWriteService.php',
    'Prospektweb\\Calc\\Services\\StandaloneCatalogPriceNormalizer' => 'lib/Services/StandaloneCatalogPriceNormalizer.php',
    'Prospektweb\\Calc\\Services\\BatchRecalculateService' => 'lib/Services/BatchRecalculateService.php',
    'Prospektweb\\Calc\\Services\\BatchPreviewFingerprintService' => 'lib/Services/BatchPreviewFingerprintService.php',
    'Prospektweb\\Calc\\Services\\ControlCenterSettingsService' => 'lib/Services/ControlCenterSettingsService.php',
    'Prospektweb\\Calc\\Services\\ModuleCapabilityRegistryService' => 'lib/Services/ModuleCapabilityRegistryService.php',
    'Prospektweb\\Calc\\Services\\ControlCenterEditorsService' => 'lib/Services/ControlCenterEditorsService.php',
    'Prospektweb\\Calc\\Services\\PresetProductAssignmentLockService' => 'lib/Services/PresetProductAssignmentLockService.php',
    'Prospektweb\\Calc\\Services\\PresetProductAssignmentPropertyAuthorityService' => 'lib/Services/PresetProductAssignmentPropertyAuthorityService.php',
    'Prospektweb\\Calc\\Services\\PresetProductAssignmentMutationGuardService' => 'lib/Services/PresetProductAssignmentMutationGuardService.php',
    'Prospektweb\\Calc\\Services\\PresetMutationCoordinatorService' => 'lib/Services/PresetMutationCoordinatorService.php',
    'Prospektweb\\Calc\\Services\\PresetLifecycleMutationService' => 'lib/Services/PresetLifecycleMutationService.php',
    'Prospektweb\\Calc\\Services\\PresetSectionSelectorService' => 'lib/Services/PresetSectionSelectorService.php',
    'Prospektweb\\Calc\\Services\\FormFirstDependencyContractService' => 'lib/Services/FormFirstDependencyContractService.php',
    'Prospektweb\\Calc\\Services\\CalcServerRequestSigner' => 'lib/Services/CalcServerRequestSigner.php',
    'Prospektweb\\Calc\\Services\\AiGatewayService' => 'lib/Services/AiGatewayService.php',
    'Prospektweb\\Calc\\Services\\AiCalculatorContextService' => 'lib/Services/AiCalculatorContextService.php',
    'Prospektweb\\Calc\\Services\\AsproAiPatchManager' => 'lib/Services/AsproAiPatchManager.php',
    'Prospektweb\\Calc\\Services\\CatalogMetaService' => 'lib/Services/CatalogMetaService.php',
    'Prospektweb\\Calc\\Services\\GlobalSymbolService' => 'lib/Services/GlobalSymbolService.php',
    'Prospektweb\\Calc\\Services\\CalculatorMutationAuthorityService' => 'lib/Services/CalculatorMutationAuthorityService.php',
    'Prospektweb\\Calc\\Services\\CalculatorSemanticMutationService' => 'lib/Services/CalculatorSemanticMutationService.php',
    'Prospektweb\\Calc\\Services\\CalculatorRefreshActionRegistryService' => 'lib/Services/CalculatorRefreshActionRegistryService.php',
    'Prospektweb\\Calc\\Services\\CalculatorGlobalMutationService' => 'lib/Services/CalculatorGlobalMutationService.php',
    'Prospektweb\\Calc\\Services\\GlobalCalculatorMutationCoordinatorService' => 'lib/Services/GlobalCalculatorMutationCoordinatorService.php',
    'Prospektweb\\Calc\\Services\\GlobalCodeRefactorService' => 'lib/Services/GlobalCodeRefactorService.php',
    'Prospektweb\\Calc\\Services\\StageGroupService' => 'lib/Services/StageGroupService.php',
    'Prospektweb\\Calc\\Handlers\\AdminHandler' => 'lib/Handlers/AdminHandler.php',
    'Prospektweb\\Calc\\Handlers\\DependencyHandler' => 'lib/Handlers/DependencyHandler.php',
    'Prospektweb\\Calc\\Diagnostic\\ModuleDiagnostic' => 'lib/Diagnostic/ModuleDiagnostic.php',
    'Prospektweb\\Calc\\Diagnostic\\GitHubClient' => 'lib/Diagnostic/GitHubClient.php',
    'Prospektweb\\Calc\\Diagnostic\\DiagnosticCache' => 'lib/Diagnostic/DiagnosticCache.php',
]);

// Примечание: Обработчик OnBuildGlobalMenu регистрируется только через persistent handler
// в install/index.php->installEvents(). Runtime регистрация через addEventHandler убрана,
// чтобы избежать дублирования пунктов меню.
