<?php
declare(strict_types=1);
if (PHP_SAPI !== 'cli' || get_current_user() !== 'cq207700') exit(1);
$_SERVER['DOCUMENT_ROOT'] = '/home/c/cq207700/prospektprint.ru/public_html';
$_SERVER['REQUEST_METHOD'] = 'GET';
define('STOP_STATISTICS', true); define('NO_KEEP_STATISTIC', true);
require $_SERVER['DOCUMENT_ROOT'].'/bitrix/modules/main/include/prolog_before.php';
require __DIR__.'/form-availability.php';
$GLOBALS['USER']->Authorize(1, false, false);
if (!$GLOBALS['USER']->IsAdmin() || !\Bitrix\Main\Loader::includeModule('prospektweb.calc')) throw new RuntimeException('Module unavailable');
use Prospektweb\Calc\Services\CalculatorVersionBundleDocumentService as Bundles;
use Prospektweb\Calc\Services\CalculatorVersionFormDocumentService as Forms;
use Prospektweb\Calc\Services\CalculatorVersionRegistryService as Registry;
use Prospektweb\Calc\Services\ControlCenterEditorsService as Editors;
const OFFSET_PRESET=12740;
const OFFSET_VERSION='v_3caf71f29edbb97234c4';
$expected=(string)($argv[1] ?? '');
$result=(new Registry())->coordinateVersionMutation(OFFSET_PRESET,function() use($expected) {
    $bundles=new Bundles();$bundle=$bundles->load(OFFSET_PRESET,OFFSET_VERSION);
    if (!$bundle || !hash_equals($bundle['contentHash'],$expected)) throw new RuntimeException('Version changed');
    $documents=$bundle['documents'];$logic=$documents['logic'];
    if (($logic['workingPresetId'] ?? 0)!==16411) throw new RuntimeException('Wrong working graph');
    $stage=null;
    foreach ($logic['runtimePayload']['elementsStore']['CALC_STAGES'] as $row) if ($row['id']===16827) $stage=$row;
    if (!$stage) throw new RuntimeException('Material stage absent');
    $tree=json_decode($stage['properties']['OPTIONS_MATERIAL']['VALUE'],true,512,JSON_THROW_ON_ERROR);
    $form=alignSheetOffsetAvailability($documents['form']['formDefinition'],$tree);
    $forms=new Forms();$old=$forms->ensure(OFFSET_PRESET,OFFSET_VERSION,null,[]);
    if ($old['formDefinition'] != $documents['form']['formDefinition']) throw new RuntimeException('Standalone form changed');
    $backup=__DIR__.'/availability-before-'.$expected.'.json';
    if (file_exists($backup)) throw new RuntimeException('Already attempted');
    if (file_put_contents($backup,json_encode(['bundle'=>$bundle,'form'=>$old],JSON_THROW_ON_ERROR|JSON_UNESCAPED_UNICODE),LOCK_EX)===false) throw new RuntimeException('Backup failed');
    $documents['form']['formDefinition']=$form;
    $preview=(new Editors())->previewVersionFormFirst(OFFSET_PRESET,$form,$old['bindingDefinition'],$documents);
    if (($preview['compile']['valid'] ?? false)!==true) throw new RuntimeException('Form compile failed');
    $bundles->inspect($documents);
    $saved=$forms->saveDraft(OFFSET_PRESET,OFFSET_VERSION,$old['revision'],$form,$old['bindingDefinition']);
    $documents['form']['formDefinition']=$saved['formDefinition'];
    $after=$bundles->save(OFFSET_PRESET,OFFSET_VERSION,$documents);
    return ['status'=>'ok','contentHash'=>$after['contentHash'],'formRevision'=>$saved['revision']];
});
file_put_contents(__DIR__.'/availability-applied.json',json_encode($result,JSON_THROW_ON_ERROR));
echo json_encode($result,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR)."\n";
