<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/lib/Documents/PdoConnection.php';
require_once dirname(__DIR__) . '/lib/Documents/DocumentSchema.php';
require_once dirname(__DIR__) . '/lib/Documents/DocumentApplication.php';
require_once dirname(__DIR__) . '/lib/Documents/DocumentCalculationDescription.php';
use Prospektweb\Calc\Documents\{PdoConnection, DocumentSchema, DocumentRepository, DocumentApplication, DocumentVersions, DocumentCalculationDescription};
$db = new PdoConnection(new PDO('sqlite::memory:')); DocumentSchema::install($db);
$repo = new DocumentRepository($db, 'site:test', 'user:1'); $checks = 0; $calls = []; $during = null;
$body = json_encode(['contract'=>'prospektweb.calculator/document-v1','schemaVersion'=>1,'id'=>'sheet','name'=>'Sheet',
    'calculations'=>[['id'=>'native-uuid','name'=>'Scheme','formulas'=>['private formula'],'authoring'=>['ai'=>'private context']]], 'form'=>new stdClass()], JSON_THROW_ON_ERROR);
$core = static function(array $request): array { $json=json_encode($request['document'],JSON_THROW_ON_ERROR); return ['documentJson'=>$json,'documentHash'=>hash('sha256',$json)]; };
$app = new DocumentApplication($repo,$core,static fn()=>[]); $app->command(['action'=>'create','documentJson'=>$body]);
$version = DocumentVersions::primaryId('sheet');
$templates = [['id'=>'card-template','zone'=>'calculator_description','name'=>'Card','prompt'=>'Prompt','model'=>'configured','privateExtra'=>'never exposed'],['id'=>'other','zone'=>'stage_description']];
$settings = static function() use (&$calls,$templates,&$during): array { $calls[]=['settings']; if ($during) $during(); return ['status'=>'ok','templates'=>$templates,'apiKey'=>'never exposed']; };
$generate = static function(array $payload) use (&$calls,&$during): array { $calls[]=$payload; if ($during) $during(); return ['status'=>'ok','text'=>'{"previewText":"Short","detailHtml":"<p>Full</p>"}','privateExtra'=>'never exposed']; };
$service = new DocumentCalculationDescription($repo,$settings,$generate);
$command = ['action'=>'calculationDescriptionTemplates','id'=>'sheet','versionId'=>$version,'expectedRevision'=>1,'calculationId'=>'native-uuid'];
$gen = array_replace($command,['action'=>'generateCalculationDescription','name'=>'Edited calculation name','prompt'=>'Card JSON','templateId'=>'card-template']);
$check = static function(bool $ok,string $label) use (&$checks): void { ++$checks; if (!$ok) throw new RuntimeException($label); };
$rejects = static function(callable $fn,int $code=0) use ($check): void { try {$fn();} catch(Throwable $e) {$check($e->getCode()===$code,$e->getMessage());return;} throw new RuntimeException('Expected rejection'); };
$before=$repo->versions()->load('sheet',$version); $history=$repo->history('sheet');
$response=$service->command($command);
$check(count($response['templates'])===1 && array_keys($response)===['templates'], 'Only calculation card templates exposed');
$check(!isset($response['templates'][0]['privateExtra']) && $response['templates'][0]['id']==='card-template', 'Template whitelist');
$response=$service->command($gen); $payload=$calls[1];
$check(array_keys($response)===['text'] && json_decode($response['text'],true)['previewText']==='Short','Only generated text exposed');
$check($payload===['zone'=>'calculator_description','templateId'=>'card-template','prompt'=>'Card JSON','context'=>['calculatorName'=>'Edited calculation name']],'Fixed zone and name-only context: no formulas, identities, bindings, secrets or document');
$check($before===$repo->versions()->load('sheet',$version) && $history===$repo->history('sheet') && !$db->inTransaction(),'Read-only and no transaction held over gateway');
$calls=[];
foreach ([['scope'=>'site:foreign'],['context'=>new stdClass()],['zone'=>'other'],['documentJson'=>$body],['entityId'=>123]] as $extra) $rejects(fn()=>$service->command($gen+$extra));
$rejects(fn()=>$service->command(array_replace($command,['expectedRevision'=>2])),409);
$rejects(fn()=>$service->command(array_replace($command,['expectedRevision'=>'1'])));
$rejects(fn()=>$service->command(array_replace($command,['calculationId'=>'foreign'])));
$rejects(fn()=>$service->command(array_replace($command,['calculationId'=>123])));
$rejects(fn()=>$service->command(array_replace($command,['versionId'=>'foreign'])),404);
$rejects(fn()=>(new DocumentCalculationDescription(new DocumentRepository($db,'site:other','user:2'),$settings,$generate))->command($command),404);
foreach (['name','prompt','templateId'] as $key) $rejects(fn()=>$service->command(array_replace($gen,[$key=>''])));
$rejects(fn()=>$service->command(array_replace($gen,['prompt'=>str_repeat('x',48001)])));
$check($calls===[],'Invalid/scoped/stale commands never call gateway');
$rejects(fn()=>(new DocumentCalculationDescription($repo,static fn()=>['status'=>'error'],$generate))->command($command),503);
$rejects(fn()=>(new DocumentCalculationDescription($repo,static fn()=>['status'=>'ok','templates'=>[['id'=>1,'zone'=>'calculator_description']]],$generate))->command($command),503);
foreach ([['status'=>'ok','text'=>''],['status'=>'error','text'=>'bad'],['status'=>'ok','text'=>str_repeat('x',100001)]] as $bad) $rejects(fn()=>(new DocumentCalculationDescription($repo,$settings,static fn()=>$bad))->command($gen),503);
$during=static function() use($repo,$version,$body):void {$repo->versions()->save('sheet',$version,1,str_replace('Sheet','Winner',$body),null,false);};
$rejects(fn()=>$service->command($gen),409);
$check(json_decode($repo->versions()->load('sheet',$version)['bodyJson'])->name==='Winner','Late response cannot overwrite concurrent edit');
$during=null; $command['expectedRevision']=2;
$index=$repo->versions()->listing('sheet');
$repo->versions()->change('sheet',$version,$index['registryRevision'],'archiveVersion',['archived'=>true]);
$rejects(fn()=>$service->command($command),409);
$entry=file_get_contents(dirname(__DIR__).'/tools/documents.php');
$check(strpos($entry,'!check_bitrix_sessid()')<strpos($entry,"'calculationDescriptionTemplates'") && strpos($entry,'!$USER->IsAdmin()')<strpos($entry,"'calculationDescriptionTemplates'"),'HTTP authentication and CSRF precede AI adapter');
echo "PASS $checks native calculation description assertions\n";
