<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/lib/Documents/PdoConnection.php';
require_once dirname(__DIR__) . '/lib/Documents/DocumentSchema.php';
require_once dirname(__DIR__) . '/lib/Documents/DocumentApplication.php';
require_once dirname(__DIR__) . '/lib/Documents/DocumentResourceCatalog.php';
use Prospektweb\Calc\Documents\{PdoConnection, DocumentSchema, DocumentRepository, DocumentApplication, DocumentVersions, DocumentResourceCatalog};
$db = new PdoConnection(new PDO('sqlite::memory:')); DocumentSchema::install($db);
$repo = new DocumentRepository($db, 'site:test', 'user:1'); $calls = 0; $during = null; $checks = 0;
$core = static fn(array $r): array => ['documentJson' => json_encode($r['document']), 'documentHash' => hash('sha256', json_encode($r['document']))];
$body = json_encode(['contract' => 'prospektweb.calculator/document-v1', 'schemaVersion' => 1, 'id' => 'sheet', 'name' => 'Sheet', 'resources' => []]);
(new DocumentApplication($repo, $core, static fn() => []))->command(['action' => 'create', 'documentJson' => $body]);
$version = DocumentVersions::primaryId('sheet');
$browse = static function () use (&$calls, &$during): array { $calls++; if ($during) $during(); return ['provider' => 'bitrix:test', 'sections' => [], 'items' => []]; };
$app = new DocumentResourceCatalog($repo, $browse);
$command = ['action' => 'resourceCatalogVersion', 'id' => 'sheet', 'versionId' => $version, 'expectedRevision' => 1];
$check = static function (bool $ok, string $message) use (&$checks): void { $checks++; if (!$ok) throw new RuntimeException($message); };
$reject = static function (callable $fn, int $code = 0) use ($check): void { try { $fn(); } catch (Throwable $e) { $check($e->getCode() === $code, $e->getMessage()); return; } throw new RuntimeException('Expected rejection'); };
$baseline = [$repo->load('sheet'), $repo->history('sheet'), $repo->versions()->listing('sheet')];
$result = $app->command($command);
$check($result['documentId'] === 'sheet' && $result['versionId'] === $version && $result['revision'] === 1 && $result['catalog']['provider'] === 'bitrix:test', 'Exact browser context');
$check($calls === 1 && $baseline === [$repo->load('sheet'), $repo->history('sheet'), $repo->versions()->listing('sheet')], 'Read did not write');
foreach (['provider', 'scope', 'actor', 'catalogId', 'documentJson', 'connectionJson'] as $field) $reject(fn() => $app->command($command + [$field => 'foreign']));
$reject(fn() => $app->command(array_replace($command, ['expectedRevision' => 0])));
$reject(fn() => $app->command(array_replace($command, ['expectedRevision' => '1'])));
$reject(fn() => $app->command(array_replace($command, ['expectedRevision' => 2])), 409);
$foreign = new DocumentResourceCatalog(new DocumentRepository($db, 'site:foreign', 'user:2'), $browse);
$reject(fn() => $foreign->command($command), 404);
$check($calls === 1, 'Invalid or foreign requests never browse');
$during = static function () use (&$during, $repo, $version, $body): void { $during = null; $repo->versions()->save('sheet', $version, 1, str_replace('Sheet', 'Winner', $body), null, false); };
$reject(fn() => $app->command($command), 409);
$check($repo->load('sheet')['revision'] === 2 && !$db->inTransaction(), 'Late conflict preserves concurrent winner');
echo "PASS $checks resource catalog application assertions\n";
