<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/lib/Documents/PdoConnection.php';
require_once dirname(__DIR__) . '/lib/Documents/DocumentSchema.php';
require_once dirname(__DIR__) . '/lib/Documents/DocumentApplication.php';
use Prospektweb\Calc\Documents\{PdoConnection, DocumentSchema, DocumentRepository, DocumentApplication};
$db = new PdoConnection(new PDO('sqlite::memory:')); DocumentSchema::install($db); DocumentSchema::install($db);
$repo = new DocumentRepository($db, 'site:test', 'user:1');
$never = static function (): never { throw new RuntimeException('Catalog must not call core/resources.'); };
$app = new DocumentApplication($repo, $never, $never);
$body = static fn(string $id): string => json_encode(['contract' => 'prospektweb.calculator/document-v1', 'schemaVersion' => 1, 'id' => $id, 'name' => 'Листовая печать']);
$checks = 0;
$check = static function (bool $condition, string $message) use (&$checks): void { $checks++; if (!$condition) { throw new RuntimeException($message); } };
$fails = static function (callable $action, int $code) use ($check): void { try { $action(); } catch (Throwable $e) { $check($e->getCode() === $code, $e->getMessage()); return; } throw new RuntimeException('Expected rejection'); };
$catalog = $app->command(['action' => 'catalog']);
$check($catalog['revision'] === 0 && $catalog['sections'] === [], 'Empty reads need no scope-row write');
$change = static function (string $action, array $values = []) use ($app, &$catalog): array {
    return $catalog = $app->command(['action' => $action, 'expectedCatalogRevision' => $catalog['revision']] + $values);
};
$root = $change('createSection', ['name' => 'Печать', 'parentId' => null])['createdId'];
$child = $change('createSection', ['name' => 'Листовая', 'parentId' => $root])['createdId'];
$leaf = $change('createSection', ['name' => 'Визитки', 'parentId' => $child])['createdId'];
$check(preg_match('/^[a-f0-9-]{36}$/', $root) === 1, 'Portable native identity');
$initial = $repo->create($body('sheet'), $child, $catalog['revision']); $catalog = $repo->catalog();
$repo->create($body('leaf'), $leaf, $catalog['revision']); $catalog = $repo->catalog();
$repo->create($body('unsectioned'));
$repo->archive('leaf', 1, true);
$other = new DocumentRepository($db, 'site:other', 'user:2'); $other->create($body('foreign'));
$otherCatalog = $other->changeCatalog('createSection', 0, ['name' => 'Private', 'parentId' => null]); $foreignId = $otherCatalog['createdId'];
$catalog = $repo->catalog(); $byId = array_column($catalog['sections'], null, 'id');
$check($catalog['calculatorCount'] === 3 && $catalog['unsectionedCount'] === 1, 'Counts are scope-local and include archive');
$check($byId[$root]['calculatorCount'] === 2 && $byId[$child]['directCalculatorCount'] === 1 && $byId[$child]['childSectionCount'] === 1, 'Tree counts include descendants');
$check($repo->registry('', 'all', 'updated_desc', 1, 30, $root)['total'] === 2, 'Branch includes descendants');
$check($repo->registry('', 'archived', 'updated_desc', 1, 30, $root)['total'] === 1, 'Branch and status compose');
$check($repo->registry('', 'all', 'updated_desc', 1, 30, '')['total'] === 1, 'Unsectioned filter');
$check($repo->registry('листовая', 'active', 'updated_desc', 1, 30, $child)['total'] === 1, 'Branch and Unicode search compose');
$fails(fn() => $repo->registry('', 'all', 'updated_desc', 1, 30, $foreignId), 404);
$fails(fn() => $change('moveToSection', ['id' => 'foreign', 'sectionId' => $root]), 404);
$fails(fn() => $change('moveToSection', ['id' => 'sheet', 'sectionId' => $foreignId]), 404);
$fails(fn() => $change('deleteSection', ['id' => $foreignId]), 404);
$fails(fn() => $change('createSection', ['name' => 'No', 'parentId' => $foreignId]), 404);
$stale = $catalog['revision']; $change('renameSection', ['id' => $child, 'name' => 'Листовая продукция']);
$fails(fn() => $app->command(['action' => 'deleteSection', 'id' => $child, 'expectedCatalogRevision' => $stale]), 409);
$fails(fn() => $repo->create($body('stale-create'), $child, $stale), 409);
$check($repo->registry('stale-create')['total'] === 0, 'Stale placement creates no partial document');
$before = $catalog['revision']; $change('renameSection', ['id' => $child, 'name' => 'Листовая продукция']);
$check($catalog['revision'] === $before, 'No-op rename does not consume revision');
$change('moveToSection', ['id' => 'sheet', 'sectionId' => $leaf]);
$change('deleteSection', ['id' => $child]);
$byId = array_column($catalog['sections'], null, 'id');
$check(!isset($byId[$child]) && $byId[$leaf]['parentId'] === $root && $catalog['calculatorCount'] === 3, 'Deletion reparents descendants without deleting calculators');
$change('deleteSection', ['id' => $leaf]);
$check($repo->registry('', 'all', 'updated_desc', 1, 30, $root)['total'] === 2, 'Direct calculators and archived calculators move up');
$change('deleteSection', ['id' => $root]);
$check($catalog['unsectionedCount'] === 3 && $catalog['sections'] === [], 'Root deletion preserves all documents at root');
$check($repo->load('sheet') === $initial && count($repo->history('sheet')) === 1, 'Folder changes never modify document hash, revision, connection or publication');
foreach ([['action' => 'catalog', 'scope' => 'site:other'], ['action' => 'createSection', 'expectedCatalogRevision' => 1, 'name' => 'x'], ['action' => 'moveToSection', 'expectedCatalogRevision' => '1', 'id' => 'sheet', 'sectionId' => null], ['action' => 'registry', 'sectionId' => 17]] as $invalid) { $fails(fn() => $app->command($invalid), 0); }
$fails(fn() => $change('createSection', ['name' => str_repeat('Я', 201), 'parentId' => null]), 0);
$check(!$db->inTransaction(), 'All successful and rejected mutations close their transaction');
DocumentSchema::install($db);
$check($repo->load('sheet') === $initial && $repo->catalog() === array_diff_key($catalog, ['createdId' => true]), 'Reinstall preserves documents and catalog metadata');
echo "PASS $checks native catalog checks\n";
