<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/lib/Documents/PdoConnection.php';
require_once dirname(__DIR__) . '/lib/Documents/DocumentSchema.php';
require_once dirname(__DIR__) . '/lib/Documents/DocumentApplication.php';
require_once dirname(__DIR__) . '/lib/Documents/DocumentStageDescription.php';
use Prospektweb\Calc\Documents\{PdoConnection, DocumentSchema, DocumentRepository, DocumentApplication, DocumentVersions, DocumentStageDescription};
$db = new PdoConnection(new PDO('sqlite::memory:')); DocumentSchema::install($db);
$repo = new DocumentRepository($db, 'site:test', 'user:1'); $checks = 0; $calls = []; $during = null;
$body = json_encode(['contract'=>'prospektweb.calculator/document-v1','schemaVersion'=>1,'id'=>'sheet','name'=>'Sheet','description'=>'Sheet description',
    'stages'=>[['id'=>'stage','name'=>'Stage']], 'parts'=>[['id'=>'part','name'=>'Part','description'=>'Part description','stages'=>['stage']]], 'form'=>new stdClass()], JSON_THROW_ON_ERROR);
$core = static function(array $request): array { $json=json_encode($request['document'],JSON_THROW_ON_ERROR); return ['documentJson'=>$json,'documentHash'=>hash('sha256',$json)]; };
$app = new DocumentApplication($repo,$core,static fn()=>[]); $app->command(['action'=>'create','documentJson'=>$body]);
$version = DocumentVersions::primaryId('sheet');
$templates = [['id'=>'stage-template','zone'=>'stage_description','name'=>'Description','prompt'=>'Prompt','model'=>'configured','privateExtra'=>'never exposed'],['id'=>'other','zone'=>'other']];
$settings = static function() use (&$calls,$templates,&$during): array { $calls[]=['settings']; if ($during) $during(); return ['status'=>'ok','templates'=>$templates,'apiKey'=>'never exposed']; };
$generate = static function(array $payload) use (&$calls,&$during): array { $calls[]=$payload; if ($during) $during(); return ['status'=>'ok','text'=>'Generated description','privateExtra'=>'never exposed']; };
$service = new DocumentStageDescription($repo,$settings,$generate);
$command = ['action'=>'stageDescriptionTemplates','id'=>'sheet','versionId'=>$version,'expectedRevision'=>1,'stageId'=>'stage'];
$gen = array_replace($command,['action'=>'generateStageDescription','name'=>'Edited stage name','prompt'=>'One paragraph','templateId'=>'stage-template']);
$check = static function(bool $ok,string $label) use (&$checks): void { ++$checks; if (!$ok) throw new RuntimeException($label); };
$rejects = static function(callable $fn,int $code=0) use ($check): void { try {$fn();} catch(Throwable $e) {$check($e->getCode()===$code,$e->getMessage());return;} throw new RuntimeException('Expected rejection'); };
$before=$repo->versions()->load('sheet',$version); $history=$repo->history('sheet');
$response=$service->command($command);
$check(count($response['templates'])===1 && array_keys($response)===['templates'], 'Only stage templates exposed');
$check(!isset($response['templates'][0]['privateExtra']) && $response['templates'][0]['id']==='stage-template', 'Template whitelist');
$response=$service->command($gen); $payload=$calls[1];
$check($response===['text'=>'Generated description'],'Only generated text exposed');
$check(array_keys($payload)===['zone','templateId','prompt','context'] && $payload['zone']==='stage_description','Fixed zone and narrow request');
$check($payload['context']===['stageName'=>'Edited stage name','detailName'=>'Part','detailPreview'=>'Part description','presetName'=>'Sheet','presetPreview'=>'Sheet description','productName'=>'','productPreview'=>''],'Server-owned context, no Bitrix/document identities');
$check($before===$repo->versions()->load('sheet',$version) && $history===$repo->history('sheet') && !$db->inTransaction(),'Read-only and no transaction held over gateway');
$calls=[];
foreach ([['scope'=>'site:foreign'],['context'=>new stdClass()],['zone'=>'other'],['documentJson'=>$body]] as $extra) $rejects(fn()=>$service->command($gen+$extra));
$rejects(fn()=>$service->command(array_replace($command,['expectedRevision'=>2])),409);
$rejects(fn()=>$service->command(array_replace($command,['expectedRevision'=>'1'])));
$rejects(fn()=>$service->command(array_replace($command,['stageId'=>'foreign'])));
$rejects(fn()=>$service->command(array_replace($command,['versionId'=>'foreign'])),404);
$rejects(fn()=>(new DocumentStageDescription(new DocumentRepository($db,'site:other','user:2'),$settings,$generate))->command($command),404);
foreach (['name','prompt','templateId'] as $key) $rejects(fn()=>$service->command(array_replace($gen,[$key=>''])));
$rejects(fn()=>$service->command(array_replace($gen,['prompt'=>str_repeat('x',48001)])));
$check($calls===[],'Invalid/scoped/stale commands never call gateway');
$rejects(fn()=>(new DocumentStageDescription($repo,static fn()=>['status'=>'error'],$generate))->command($command),503);
foreach ([['status'=>'ok','text'=>''],['status'=>'error','text'=>'bad'],['status'=>'ok','text'=>str_repeat('x',100001)]] as $bad) $rejects(fn()=>(new DocumentStageDescription($repo,$settings,static fn()=>$bad))->command($gen),503);
$during=static function() use($repo,$version,$body):void {$repo->versions()->save('sheet',$version,1,str_replace('Sheet','Winner',$body),null,false);};
$rejects(fn()=>$service->command($gen),409);
$check(json_decode($repo->versions()->load('sheet',$version)['bodyJson'])->name==='Winner','Late response cannot overwrite concurrent edit');
$entry=file_get_contents(dirname(__DIR__).'/tools/documents.php');
$check(strpos($entry,'!check_bitrix_sessid()')<strpos($entry,"'stageDescriptionTemplates'") && strpos($entry,'!$USER->IsAdmin()')<strpos($entry,"'stageDescriptionTemplates'"),'HTTP authentication before AI adapter');
echo "PASS $checks native stage description assertions\n";
