<?php
declare(strict_types=1);
require_once __DIR__.'/document_preparation_catalog_test.php';
require_once __DIR__.'/../lib/Documents/PreparationPropertyLinks.php';
use Prospektweb\Calc\Documents\{PreparationPriceOverrides as Prices,PreparationPropertyLinks as Links,DocumentPreparationPropertyPlan as Properties};
$state=$v['state'];$types=$v['priceTypeIds'];$slots=Prices::slots($state,$types);$purchase=$slots[0];$sale=$slots[1];
$custom=Prices::resolve($state,$types,[$purchase['key']=>'55.125',$sale['key']=>'777.12345678']);
ok($custom['state']['purchasingPrice']['value']===55.125,'Purchase override independent');
ok(count(array_filter($custom['state']['prices'],fn($p)=>$p['price']===777.12345678))===1,'Only exact sale interval overridden');
ok(count($custom['state']['prices'])===count($state['prices']),'Every range retained');
$new=$state;$new['purchasingPrice']['value']=200;$next=Prices::resolve($new,$types,[$purchase['key']=>'55.125']);
ok($next['state']['purchasingPrice']['value']===55.125&&$next['slots'][0]['calculated']===200,'New calculated base preserves manual slot');
$new['purchasingPrice']['value']=0;$next=Prices::resolve($new,$types,[$purchase['key']=>'0']);ok($next['slots'][0]['differencePercent']===0,'Zero/zero percent');
$next=Prices::resolve($new,$types,[$purchase['key']=>'5']);ok($next['slots'][0]['differencePercent']===null,'Zero/nonzero percent undefined');
$new=$state;$new['purchasingPrice']['currency']='USD';$next=Prices::resolve($new,$types,[$purchase['key']=>'5']);ok($next['orphanKeys']===[$purchase['key']],'Currency change does not adopt manual price');
foreach(['-1','NaN','1e3','1.123456789',1] as $bad)reject(fn()=>Prices::amount($bad));
$s=['f'=>['visible'=>true],'inactive'=>['visible'=>false]];
ok(Properties::savedInput((object)[],'f',$s)['state']==='absent','Missing value distinct');
ok(Properties::savedInput((object)['f'=>''],'f',$s)['state']==='explicit-empty','Active empty is intended');
ok(Properties::savedInput((object)['inactive'=>''],'inactive',$s)['intended']===false,'Inactive placeholder does not clear');
ok(Properties::savedInput((object)['f'=>false],'f',$s)['intended']===true,'Active false is intended');
$schema=fn($id,$type='L')=>['ID'=>(string)$id,'IBLOCK_ID'=>'15','NAME'=>'Property'.$id,'CODE'=>'CALC_P'.$id,'ACTIVE'=>'Y','PROPERTY_TYPE'=>$type,'USER_TYPE'=>'','MULTIPLE'=>'N'];
$cat=['products'=>14,'schemas'=>[1=>$schema(1),2=>$schema(2),3=>$schema(3)],'choices'=>[1=>[['ID'=>11,'XML_ID'=>'4+0','VALUE'=>'4+0']],2=>[['ID'=>21,'XML_ID'=>'one','VALUE'=>'One side']],3=>[['ID'=>31,'XML_ID'=>'x','VALUE'=>'X']]]];
$edge=['sourceId'=>1,'targetId'=>2,'values'=>[['source'=>[11],'target'=>[21]]]];
$links=Links::validate([$edge],$cat,[1]);$rows=[['scope'=>'selected_offer','propertyId'=>1,'fieldId'=>'color','values'=>[11]]];
ok(Links::expand($rows,$links,$cat)[1]['values']===[21],'Exact enum mapping expands');
$deleted=$cat;unset($deleted['schemas'][2]);ok(Links::expand($rows,$links,$deleted)===$rows,'Deleted target ignored without clearing');
$deleted=$cat;unset($deleted['schemas'][1]);reject(fn()=>Links::expand($rows,$links,$deleted));
reject(fn()=>Links::validate([$edge],$cat,[1,2]));
reject(fn()=>Links::validate([$edge,$edge],$cat,[1]));
reject(fn()=>Links::validate([$edge,['sourceId'=>2,'targetId'=>1,'values'=>[]]],$cat,[]));
reject(fn()=>Links::validate([$edge,['sourceId'=>2,'targetId'=>3,'values'=>[]]],$cat,[]));
$deleted=$cat;$deleted['choices'][2]=[];reject(fn()=>Links::expand($rows,$links,$deleted));
$deleted=$cat;$deleted['schemas'][2]['PROPERTY_TYPE']='N';reject(fn()=>Links::expand($rows,$links,$deleted));
echo "PASS $checks combined generation and settings assertions\n";
